"use client";
import Link from "next/link"; import { useCallback, useEffect, useRef, useState } from "react"; import type { Issue } from "@/lib/content";
type PdfDocument = { numPages:number; getPage:(n:number)=>Promise<{getViewport:(o:{scale:number})=>{width:number;height:number};render:(o:{canvasContext:CanvasRenderingContext2D;viewport:unknown})=>{promise:Promise<void>}}> };
export function PdfReader({issue,initialPage}:{issue:Issue;initialPage:number}){
 const [pdf,setPdf]=useState<PdfDocument>(); const [error,setError]=useState(false); const [scale,setScale]=useState(1); const session=useRef(crypto.randomUUID()); const started=useRef(Date.now()); const active=useRef(0); const lastTick=useRef(Date.now()); const lastActivity=useRef(Date.now());
 const track=useCallback((event:string,extra:Record<string,unknown>={})=>{try{const entry_id=new URL(location.href).searchParams.get("entry_id")||undefined;const body=JSON.stringify({event,entry_id,session_id:session.current,issue_id:issue.issue_id,active_engagement_seconds:Math.round(active.current/1000),elapsed_session_seconds:Math.round((Date.now()-started.current)/1000),...extra});navigator.sendBeacon?.("/api/events",new Blob([body],{type:"application/json"}))||fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body,keepalive:true}).catch(()=>{});}catch{}},[issue.issue_id]);
 useEffect(()=>{let cancelled=false;import("pdfjs-dist").then(async p=>{p.GlobalWorkerOptions.workerSrc="/pdf.worker.min.mjs";try{const doc=await p.getDocument(issue.local_pdf_path||issue.pdf_url||"").promise;if(!cancelled){setPdf(doc as PdfDocument);track("read_start");}}catch{if(!cancelled){setError(true);track("reader_error");}}});return()=>{cancelled=true}},[issue.local_pdf_path,issue.pdf_url,track]);
 useEffect(()=>{const activity=()=>lastActivity.current=Date.now();const tick=()=>{const now=Date.now();if(!document.hidden&&now-lastActivity.current<30000)active.current+=now-lastTick.current;lastTick.current=now};const interval=setInterval(()=>{tick();track("engagement_heartbeat")},15000);const flush=()=>{tick();track("engagement_heartbeat",{final:true})};["scroll","pointerdown","touchstart","keydown"].forEach(e=>addEventListener(e,activity,{passive:true}));document.addEventListener("visibilitychange",flush);addEventListener("pagehide",flush);return()=>{clearInterval(interval);["scroll","pointerdown","touchstart","keydown"].forEach(e=>removeEventListener(e,activity));document.removeEventListener("visibilitychange",flush);removeEventListener("pagehide",flush)}},[track]);
 useEffect(()=>{if(pdf&&initialPage<=pdf.numPages)setTimeout(()=>document.getElementById(`page-${initialPage}`)?.scrollIntoView(),100)},[pdf,initialPage]);
 return <main className="reader"><div className="reader-toolbar"><Link href={`/issues/${issue.issue_id}`}>← 返回本期</Link><strong>{issue.year}.{String(issue.month).padStart(2,"0")}</strong><div className="zoom"><button onClick={()=>setScale(s=>Math.max(.75,s-.25))} aria-label="縮小">−</button><button onClick={()=>setScale(1)}>重設</button><button onClick={()=>setScale(s=>Math.min(2,s+.25))} aria-label="放大">＋</button></div></div>{error?<div className="reader-error"><span className="mark">SHH</span><h1>刊物檔案尚未就緒</h1><p>目前找不到這一期的 PDF，請稍後重試或返回本期資訊。</p><div className="actions"><button className="button primary" onClick={()=>location.reload()}>重新載入</button><Link className="button secondary" href={`/issues/${issue.issue_id}`}>回本期</Link>{issue.pdf_url&&<a className="button secondary" href={issue.pdf_url}>原始 PDF</a>}</div></div>:!pdf?<div className="loading">正在準備刊物…</div>:<div className="pdf-pages" style={{width:`${scale*100}%`}}>{Array.from({length:pdf.numPages},(_,i)=><PdfPage pdf={pdf} page={i+1} key={i}/>)}</div>}</main>
}
function PdfPage({pdf,page}:{pdf:PdfDocument;page:number}){const ref=useRef<HTMLCanvasElement>(null);const [near,setNear]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>entry.isIntersecting&&setNear(true),{rootMargin:"800px"});observer.observe(el);return()=>observer.disconnect()},[]);useEffect(()=>{if(!near||!ref.current)return;let cancelled=false;pdf.getPage(page).then(p=>{if(cancelled||!ref.current)return;const viewport=p.getViewport({scale:1.5});const canvas=ref.current;canvas.width=viewport.width;canvas.height=viewport.height;p.render({canvasContext:canvas.getContext("2d")!,viewport}).promise.catch(()=>{});});return()=>{cancelled=true}},[near,page,pdf]);return <figure id={`page-${page}`} className="pdf-page"><canvas ref={ref}/><figcaption>{page}</figcaption></figure>}
